### ISSUE TITLE
the image has been remove 

### ISSUE THREAD

**Issue by teguh87** [david-romero/spring-boot-mongo-docker#1]
Hi 

I'm using your docker image for spring boot mongo but docker has confirmed me about : 

<pre>
ERROR: pull access denied for davromalc/spring-boot-mongo-docker, repository does not exist or may require 'docker login'
</pre>

Could you confirm where the image right know?

**Comment by david-romero** [comment]
Hi @teguh87 ,

First, I you want build the docker image, you only have to clone the project and execute the command: `mvn clean install`

Anyway, I've pushed the image to Docker Hub. You can now pull the image :smile:

**Comment by teguh87** [comment]
Ok Thanks but I have the better solution for this issue,

I'm changing the app configuration not using the spring-boot-mongo-docker image, but manually exec the maven command in docker-compose.yml configuration 

<pre>
app:
    restart: always
    build: ./app # relative path of the project
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose: 
      - "8080"
    command: mvn spring-boot:run
    depends_on:
      - nginx
      - mongo
</pre>

Thanks very well and I'll close the issue
